### ISSUE TITLE
upgrade to latest version of react

### ISSUE THREAD

**Issue by FPurchess** [tgecho/react-prosemirror#5]
It would be great if react-prosemirror would support the latest version of react.
I'm currently getting a warning for https://github.com/tgecho/react-prosemirror/blob/master/index.js#L36 which tells me to strip `getDOMNode()` and use  `this.refs.pm.appendChild(this.pm.wrapper)` instead.

**Comment by owend** [comment]
:+1:  Because react is a peerDependency, it conflicts with other libs that require latest react.  Also because this is depending on git head version of prosemirror, I ran into the following errors today:

```
ERROR in ./demo/demo.jsx
Module not found: Error: Cannot resolve module 'prosemirror/src/convert/to_markdown' in /Projects/react-prosemirror/demo
 @ ./demo/demo.jsx 17:0-46
```

Those files have moved (convert/to_markdown is gone).  I fixed that and ran into this error:

```
ERROR in ./~/prosemirror/~/markdown-it/~/entities/maps/entities.json
Module parse failed: /Projects/react-prosemirror/node_modules/prosemirror/node_modules/markdown-it/node_modules/entities/maps/entities.json Line 1: Unexpected token :
You may need an appropriate loader to handle this file type.
```

So I fixed that by adding the json-loader plugin to the webpack config file. 

I can open a PR that fixes these issues and updates react dependency to 0.14.2

**Comment by FPurchess** [comment]
Great! Thanks a lot! Btw: are you planning a new release on npm?

**Comment by tgecho** [comment]
Thanks for reporting it!

I'm not really planning to push anything to NPM until ProseMirror itself is published. I seems odd to have a published package depend on an unpublished one.

**Comment by FPurchess** [comment]
Ah, i see.
